Repository githubschool/data-hearing, pull requests merged in 2018-04, with the labels that each got.

#15 change slide for shub8703
  _posts/0000-01-09-shub8703.md
Labels: enhancement

#9 Change slide for GitHubTeacher
  _posts/0000-01-16-githubteacher.md
Labels: enhancement

#17 change the title and caption for AK-ESRI' slide
  _posts/0000-01-15-ak-esri.md
Labels: enhancement

#19 caption is changed
  _posts/0000-01-06-skrishn.md
Labels: helloWorld

#12 Change slide for ReddyNeeta
  _posts/0000-01-12-reddyneeta.md
Labels: enhancement

#13 Change caption for Tao's slide
  _posts/0000-01-02-jimmieego.md
Labels: enhancement

#18 AshP Made edits to slide: updated title and caption
  _posts/0000-01-10-AshPengelly.md
Labels: good first issue

#8 Title for future me
  _posts/0000-01-03-intheswim.md
Labels: enhancement

#10 Found a dog. Why it is so sad?
  _posts/0000-01-13-Lyuye.md
Labels: question
